### ISSUE TITLE
feat: codeSandbox examples app

### ISSUE THREAD

**Issue by andykenward** [Stinkstudios/npm-packages#72]
To let people try out an app without having to install it.

https://codesandbox.io/

https://codesandbox.io/docs/importing

Perhaps have Travis CI use the API to export 
https://codesandbox.io/docs/importing#export-with-cli

**Comment by tyreer** [comment]
Running the `npx codesandbox ./` command from the root folder of a project generated via `npx create-react-app my-app --scripts-version @stinkstudios/react-scripts` works great, and results in something like this: https://codesandbox.io/s/m57n83r7n8

But the first time you deploy to CodeSandbox, the CLI asks you to login via GitHub and then enter a token you copy from a CodeSandbox browser link. Not sure how that process would work if the command were triggered via Travis CI

@andykenward,  do you think invoking the CLI via Travis is worth looking more into?

**Alternatives might be:**
+ Use their Define API via Travis CI. Downside is that this seems to require you to specify each file to include in the sandbox as an individual JSON value.
  + https://codesandbox.io/docs/importing#define-api

+ Just include a link in the readme to a sample project like I've deployed above. Not sure how we'd keep that up to date apart from adding the task for contributors in the releasing instructions:
https://github.com/Stinkstudios/npm-packages/blob/master/CONTRIBUTING.md#releasingthat contributors

**Comment by andykenward** [comment]
@tyreer I think we can use the codesandbox importing api and send the build output from the react-scripts package on travis-ci.

**Comment by andykenward** [comment]
I was wrong, @tyreer .  It should be the output from running [`yarn create-react-app`](https://github.com/Stinkstudios/npm-packages/blob/7b3bc0a5a6d3912267261325e7d3e923efc66eec/package.json#L7) instead off build. So the `my-app` folder is imported by codesandbox.
